project:
  type: website
website:
  title: "Datafigure"
  navbar:
    search: false
    left:
      - href: index.qmd
        text: Workshops
      - href: past.qmd
        text: Past workshops
      - contact.qmd
  sidebar:
    logo: "round.jpg"
    title: "Andres Karjus"
    style: "docked"

format:
  html:
    theme: lux
    css: styles.css
    toc: true


