project:
  type: website
  output-dir: docs
website:
  title: "Datafigure"
  favicon: "fav.png"
  navbar:
    search: false
    left:
      - href: index.qmd
        text: Workshops
      - href: past.qmd
        text: Past workshops
      - consulting.qmd
      - href: media.qmd
        text: Media coverage
      - contact.qmd
format:
  html:
    theme: sandstone
    css: styles.css


